// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUcixCmC40_3HtetBSltsH7mqZB2lue1M',
    appId: '1:784959847395:web:ffd2e3e56e8cc2889c3ed6',
    messagingSenderId: '784959847395',
    projectId: 'chat-application-17dfc',
    authDomain: 'chat-application-17dfc.firebaseapp.com',
    storageBucket: 'chat-application-17dfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6mf3LboQdrWRt7HRbSvO8XYkAP3u2RY',
    appId: '1:784959847395:android:8b74c152ce21f52f9c3ed6',
    messagingSenderId: '784959847395',
    projectId: 'chat-application-17dfc',
    storageBucket: 'chat-application-17dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7L0NuwpTKBTzRkNDigdnkDCxaMOOzA08',
    appId: '1:784959847395:ios:a5c6d428c1f6749f9c3ed6',
    messagingSenderId: '784959847395',
    projectId: 'chat-application-17dfc',
    storageBucket: 'chat-application-17dfc.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7L0NuwpTKBTzRkNDigdnkDCxaMOOzA08',
    appId: '1:784959847395:ios:a5c6d428c1f6749f9c3ed6',
    messagingSenderId: '784959847395',
    projectId: 'chat-application-17dfc',
    storageBucket: 'chat-application-17dfc.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUcixCmC40_3HtetBSltsH7mqZB2lue1M',
    appId: '1:784959847395:web:bc1a5ef3238408f59c3ed6',
    messagingSenderId: '784959847395',
    projectId: 'chat-application-17dfc',
    authDomain: 'chat-application-17dfc.firebaseapp.com',
    storageBucket: 'chat-application-17dfc.firebasestorage.app',
  );
}
